version: '3'
services:
  selenium:
    restart: always
    image: "selenium/standalone-chrome-debug"
    ports:
      - 4446:4446
      - 5902:5902
    volumes:
      - /dev/shm:/dev/shm
  app:
    build:
      context: .
      dockerfile: build/Dockerfile
    depends_on:
      - selenium
    volumes:
      - .:/var/www/
    network_mode: "host"
